## CATEGORY

### LIST
GET http://localhost:5000/api/v1/categories/

### DETAIL
GET http://localhost:5000/api/v1/category/2


### SAVE
POST http://localhost:5000/api/v1/category/
Content-Type: application/json

{
    "name" : "Undetected"
}

### UPDATE
PATCH http://localhost:5000/api/v1/category/5
Content-Type: application/json

{
    "name" : "Tech and IT"
}

### DELETE
DELETE http://localhost:5000/api/v1/category/5

### GET EVENTS BY CATEGORY
GET http://localhost:5000/api/v1/category/2/events